
#       ------------ +  ActiCraft Socials  + ------------   #
#                                                           #
#                            Config                         #
#                                                           #
#       --------- + ------------------------- + ---------   #

# Socials
YouTube: ""
Twitter: ""
Discord: ""
Instagram: ""
WEBSITE: "https://acticraft.net"

#It would be really nice to take 1min and rate this plugin.
#In case you have any ideas for plugin updates please send me a DM on Discord -> "Mat#5000".