
#       ------------ +  ActiCraft Socials  + ------------   #
#                                                           #
#                            Config                         #
#                                                           #
#       --------- + ------------------------- + ---------   #

# Socials
YOUTUBE: "Your Youtube Link here"
TWITTER: "Your Twitter Link here"
DISCORD: "Your discord server invite here"
INSTAGRAM: "Your Instagram Link here"
WEBSITE: "Your Website Link here"
TIKTOK: "Your TikTok Link here"

#It would be really nice to take 1min and rate this plugin.
#In case you have any ideas for plugin updates please send me a DM on Discord -> "Mat#5000".
# Special thanks to JernejTDO and JoshuaLovesCode for some help with development!